version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: saturday
    time: "20:00"
    timezone: Asia/Shanghai
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - Leecason
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: rollup
    versions:
    - 2.38.0
    - 2.38.1
    - 2.38.5
    - 2.39.0
    - 2.40.0
    - 2.41.2
    - 2.42.1
    - 2.43.0
    - 2.44.0
    - 2.45.1
  - dependency-name: "@vue/cli-plugin-typescript"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-plugin-router"
    versions:
    - 4.5.11
  - dependency-name: vue-router
    versions:
    - 3.4.9
  - dependency-name: rollup-plugin-typescript2
    versions:
    - 0.29.0
